Code/mysite/lib/urls.py
from django.urls import path
from . import views

app_name='lib'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/',views.detail,name='detail'),
    path('addBook/',views.addBook,name='addBook'),
    path('delBook/<int:book_id>',views.deleteBook,name='delBook'),
]

Code/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('lib/',include('lib.urls')),
    path('admin/', admin.site.urls),
]

Code/mysite/lib/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

Code/mysite/lib/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    return HttpResponse("hello world!")

def detail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {'book_list':book_list}
    return render(request,'lib/detail.html',context)

def addBook(request):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    from django.utils import timezone
    temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
    temp_book.save()

    #redirect
    return HttpResponseRedirect(reverse('lib:detail'))#like /lib/detail/

def deleteBook(request, book_id):
    bookID = book_id
    Book.objects.filter(id=bookID).delete()
    return HttpResponseRedirect(reverse('lib:detail'))

Code/mysite/lib/templates/lib/detail.html
<h1>Book List</h1>
<table>
    <tr>
        <td>book name</td>
        <td>author</td>
        <td>publish company</td>
        <td>publish time</td>
    </tr>

{% for book in book_list.all %}
    <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>
        <td><a href="{% url 'lib:delBook' book.id %}">delete</a></td>
    </tr>
{% endfor %}
</table>

</table>

<form action="{% url 'lib:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>book name</span><input type="text"  name="name"></p>
    <p><span>author</span><input type="text"  name="author"></p>
    <p><span>publish company</span><input type="text"  name="pub_house"></p>
    <input type="submit" value="??">
</form>